//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingIT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class for_managerA
    {
        public decimal area { get; set; }
        public decimal cost { get; set; }
        public decimal valAddFactor { get; set; }
        public decimal Expr1 { get; set; }
        public System.DateTime dateStart { get; set; }
        public System.DateTime dateEnd { get; set; }
        public Nullable<decimal> Result { get; set; }
        public int idMall { get; set; }
    }
}
