//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingIT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class for_employers
    {
        public string surname { get; set; }
        public string name { get; set; }
        public string middlename { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string sex { get; set; }
        public string title { get; set; }
        public string phone { get; set; }
        public byte[] photo { get; set; }
        public int idEmployer { get; set; }
    }
}
