//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingIT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class rent
    {
        public int idRent { get; set; }
        public int idTenant { get; set; }
        public int idMall { get; set; }
        public int idEmployer { get; set; }
        public string hallNum { get; set; }
        public int idStatus { get; set; }
        public System.DateTime dateStart { get; set; }
        public System.DateTime dateEnd { get; set; }
        public int idHall { get; set; }
    
        public virtual employers employers { get; set; }
        public virtual halls halls { get; set; }
        public virtual statuses statuses { get; set; }
        public virtual tenants tenants { get; set; }
    }
}
