//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class forMalls
    {
        public string title { get; set; }
        public string StatusMall { get; set; }
        public int hallsCount { get; set; }
        public string address { get; set; }
        public decimal cost { get; set; }
        public int floorsCount { get; set; }
        public decimal valAddedFactor { get; set; }
        public int idMall { get; set; }
        public byte[] icon { get; set; }
        public int idStatus { get; set; }
    }
}
