//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class getHallsView
    {
        public int idStatus { get; set; }
        public string title { get; set; }
        public int floor { get; set; }
        public string hallNum { get; set; }
        public int idMall { get; set; }
        public decimal area { get; set; }
        public int status { get; set; }
        public decimal valAddFactor { get; set; }
        public decimal cost { get; set; }
        public int idHall { get; set; }
    }
}
