//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class halls
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public halls()
        {
            this.rent = new HashSet<rent>();
        }
    
        public string hallNum { get; set; }
        public int idMail { get; set; }
        public int floor { get; set; }
        public int status { get; set; }
        public decimal area { get; set; }
        public decimal cost { get; set; }
        public decimal valAddedFactor { get; set; }
    
        public virtual malls malls { get; set; }
        public virtual statuses statuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rent> rent { get; set; }
    }
}
