//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingIT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class KingITDBEntities : DbContext
    {
        public KingITDBEntities()
            : base("name=KingITDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<employers> employers { get; set; }
        public virtual DbSet<halls> halls { get; set; }
        public virtual DbSet<malls> malls { get; set; }
        public virtual DbSet<postes> postes { get; set; }
        public virtual DbSet<rent> rent { get; set; }
        public virtual DbSet<statuses> statuses { get; set; }
        public virtual DbSet<tenants> tenants { get; set; }
        public virtual DbSet<CITY> CITY { get; set; }
        public virtual DbSet<forMalls> forMalls { get; set; }
    
        public virtual ObjectResult<Nullable<int>> login_proc(string user_login, string user_pass)
        {
            var user_loginParameter = user_login != null ?
                new ObjectParameter("user_login", user_login) :
                new ObjectParameter("user_login", typeof(string));
    
            var user_passParameter = user_pass != null ?
                new ObjectParameter("user_pass", user_pass) :
                new ObjectParameter("user_pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("login_proc", user_loginParameter, user_passParameter);
        }
    
        public virtual int RentOrBookPavilion(string id_pavilion, Nullable<int> id_shopping_center, Nullable<int> status)
        {
            var id_pavilionParameter = id_pavilion != null ?
                new ObjectParameter("id_pavilion", id_pavilion) :
                new ObjectParameter("id_pavilion", typeof(string));
    
            var id_shopping_centerParameter = id_shopping_center.HasValue ?
                new ObjectParameter("id_shopping_center", id_shopping_center) :
                new ObjectParameter("id_shopping_center", typeof(int));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RentOrBookPavilion", id_pavilionParameter, id_shopping_centerParameter, statusParameter);
        }
    }
}
