//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class malls
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public malls()
        {
            this.halls = new HashSet<halls>();
        }
    
        public int idMall { get; set; }
        public string title { get; set; }
        public int idStatus { get; set; }
        public int hallsCount { get; set; }
        public string address { get; set; }
        public decimal cost { get; set; }
        public decimal valAddedFactor { get; set; }
        public int floorsCount { get; set; }
        public byte[] icon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<halls> halls { get; set; }
        public virtual statuses statuses { get; set; }
    }
}
